package enums;

public enum Orgao {
    ADEAL("AGENCIA DE DEFESA E INSPECAO AGROPECUARIA ESTADO DE ALAGOAS"),
    AMGESP("AGENCIA DE MODERNIZACAO DA GESTAO DE PROCESSOS"),
    ARSAL("AGENCIA REGULADORA DE SERVICOS PUBLICOS DO ESTADO DE ALAGOAS"),
    ALPREV("AL PREVIDENCIA"),
    CARHP("ALAGOAS PREVIDENCIA"),
    CGE("COMPANHIA ALAGOANA DE RECUROS HUMANOS E PATRIMONIAIS"),
    CBM_AL("CONTROLADORIA GERAL DO ESTADO CORPO DE BOMBEIROS MILITAR DE ALAGOAS"),
    DER("DEPARTAMENTO DE ESTRADAS DE RODAGEM"),
    DETRAN("DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS"),
    DITEAL("DIRETORIA DE TEATROS DO ESTADO DE ALAGOAS"),
    FAPEAL("FUNDACAO DE AMPARO A PESQUISA DE ALAGOAS"),
    GMAL("GABINETE DO GOVERNADOR"),
    CVG("GABINETE DO VICE GOVERNADOR"),
    IPASEAL("INSTITUTO DE ASSISTENCIA A SAUDE DOS SERVIDORES DO ESTADO DE"),
    IDERAL("INSTITUTO DE DESENVOLVIMENTO RURAL E ABASTECIMENTO DE ALAGOA"),
    EMATER("INSTITUTO DE INOVACAO PARA O DESENV RURAL SUSTENTAVEL"),
    INMEQ("INSTITUTO DE METROLOGIA E QUALIDADE DE ALAGOAS"),
    PROCON("INSTITUTO DE PROTECAO E DEFESA DO CONSUMIDOR"),
    ITEC("INSTITUTO DE TECNOLOGIA EM INFORMATICA E INF DE ALAGOAS"),
    ITERAL("INSTITUTO DE TERRAS E REFORMA AGRARIA DE ALAGOAS"),
    IMA("INSTITUTO DO MEIO AMBIENTE DO ESTADO DE ALAGOAS"),
    IZP("INSTITUTO ZUMBI DOS PALMARES"),
    LIFAL("LABORATORIO INDUSTRIAL FARMACEUTICO DE ALAGOAS AS"),
    PO("PERICIA OFICIAL DO ESTADO DE ALAGOAS"),
    PC("POLICIA CIVIL DO ESTADO DE ALAGOAS"),
    PM("POLICIA MILITAR DE ALAGOAS"),
    PGE("PROCURADORIA GERAL DO ESTADO"),
    SEAGRI("SEC DE ESTADO DA AGRICULTURA PECUARIA PESCA E AQUICULTURA"),
    SEADES("SECRETARIA DE ESTADO DA ASSISTENCIA E DESENVOLVIMENTO SOCIAL"),
    SECTI("SECRETARIA DE ESTADO DA CIENCIA DA TECNOLOGIA E DA INOVACAO"),
    SECOM("SECRETARIA DE ESTADO DA COMUNICACAO"),
    SECULT("SECRETARIA DE ESTADO DA CULTURA"),
    SEDUC("SECRETARIA DE ESTADO DA EDUCACAO"),
    SEFAZ("SECRETARIA DE ESTADO DA FAZENDA"),
    SEINFRA("SECRETARIA DE ESTADO DA INFRA ESTRUTURA"),
    SEMUDH("SECRETARIA DE ESTADO DA MULHER CIDADANIA DIREITOS HUMANOS"),
    SESAU("SECRETARIA DE ESTADO DA SAUDE"),
    SSP("SECRETARIA DE ESTADO DA SEGURANCA PUBLICA"),
    SEPREV("SECRETARIA DE ESTADO DE PREVENCAO A VIOLENCIA"),
    SERIS("SECRETARIA DE ESTADO DE RESSOCIALIZACAO E INCLUSAO SOCIAL"),
    SETRAND("SECRETARIA DE ESTADO DE TRANSPORTE E DESENVOLVIMENTO URBANO"),
    SEDETUR("SECRETARIA DE ESTADO DO DESENVOLVIMENTO ECONOMICO E TURISMO"),
    SELAJ("SECRETARIA DE ESTADO DO ESPORTE LAZER E JUVENTUDE"),
    SEMARH("SECRETARIA DE ESTADO DO MEIO AMBIENTE E RECURSOS HIDRICOS"),
    SEPLAG("SECRETARIA DE ESTADO DO PLANEJAMENTO GESTAO E PATRIMONIO"),
    SETE("SECRETARIA DE ESTADO DO TRABALHO E EMPREGO"),
    SERVEAL("SERVICOS DE ENGENHARIA DE ALAGOAS S/A"),
    UNEAL("UNIVERSIDADE ESTADUAL DE ALAGOAS"),
    UNCISAL("UNIVERSIDADE ESTADUAL DE CIENCIAS DA SAUDE DE ALAGOAS");


    private final String descricao;
    Orgao(String descricao){
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}